### ISSUE TITLE
Ability to remove read only users

### ISSUE THREAD

**Issue by gonzague** [coolriku/Unifi-Tools#2]
Hey, thanks for your script! Very useful and quite a shame that the feature doesn't exist in the normal controller.

Would a lot of changes be required to remove a read-only user from all sites?

**Comment by gonzague** [comment]
I found a work around : promote the read only user to Super admin , then delete it :-)

**Comment by coolriku** [comment]
> I found a work around : promote the read only user to Super admin , then delete it :-)

Thanks for the workaround! 
Closing thuis issue
